
    <div class="footer__bottom-country ">
        <img src="<?php echo $block->getUrl("media/images/")?>country.png" class="footer__bottom-country-img ">
        
        
        <h3>Choose your country</h3>
    </div>
    <ul class="footer__bottom-list">
        <li class="footer__bottom-item">
            <a href="" class="footer__bottom-item-link">Terms &amp; Conditions</a>
        </li>
        <li class="footer__bottom-item">
            <a href="" class="footer__bottom-item-link">Privacy Policy</a>
        </li>
        <li class="footer__bottom-item">
            <a href="" class="footer__bottom-item-link">Imprint</a>
        </li>
        <li class="footer__bottom-item">
            <a href="" class="footer__bottom-item-link">Sitemap</a>
        </li>
    </ul>
    <div class="footer__bottom-year">
        Glamira 2008 - 2022
    </div>

    