
<li class="footer__contact-badges">
    <div class="row">
        <img src="<?php echo $block->getUrl("media/images/")?>topic-11.png" class="footer__contact-badges-img ">
        <img src="<?php echo $block->getUrl("media/images/")?>topic-12.png" class="footer__contact-badges-img ">
        <img src="<?php echo $block->getUrl("media/images/")?>topic-13.png" class="footer__contact-badges-img ">      
    </div>
</li>
    