 
<img src="<?php echo $block->getUrl("media/images/")?>logo-big.png" >                

<div class="footer__contact-rating">
    <h2>Reviews</h2>
    <ul class="footer__contact-star-list">
        <li class="footer__contact-star-item">
            <img src="<?php echo $block->getUrl("media/images/")?>star.png" >   
        </li>
        <li class="footer__contact-star-item">
            <img src="<?php echo $block->getUrl("media/images/")?>star.png" >   
        </li>
        <li class="footer__contact-star-item">
            <img src="<?php echo $block->getUrl("media/images/")?>star.png" >   
        </li>
        <li class="footer__contact-star-item">
            <img src="<?php echo $block->getUrl("media/images/")?>star.png" >   
        </li>
         <li class="footer__contact-star-item">
            <img src="<?php echo $block->getUrl("media/images/")?>star.png" >   
        </li>                     
    </ul>
    <p class="footer__contact-rating-point">4.7</p>
</div>
<div class="footer__social">
    <a href="" class="footer__social-link">
    <img src="<?php echo $block->getUrl("media/images/")?>fb.png" >   
    </a>
    <a href="" class="footer__social-link">
        <img src="<?php echo $block->getUrl("media/images/")?>twitter.png" >   
    </a>
    <a href="" class="footer__social-link">
        <img src="<?php echo $block->getUrl("media/images/")?>insatgram.png" >   
      
    </a>
</div>

