
    <ul class="header__navbar-list hide-on-mobi show-on-pc-flex ">
        <li class="header__navbar-item header__navbar-separate">
            <a href="" class="header__navbar-item-link header-active-2">De</a>
        </li>
        <li class="header__navbar-item header__navbar-separate">
            <a href="" class="header__navbar-item-link">Fr</a>
        </li>
        <li class="header__navbar-item">
            <a href="" class="header__navbar-item-link">It</a>
        </li>                     
    </ul>           

    <ul class="header__mobile-list">
        <li class="header__mobile-item hide-on-mobi show-on-pc">
            <img src="<?php echo $block->getUrl("media/images/")?>search.png"/>        
        </li>
        <li class="header__mobile-item hide-on-mobi show-on-pc">
            <img src="<?php echo $block->getUrl("media/images/")?>acc.png"/>      
        </li>
        <li class="header__mobile-item">
            <img src="<?php echo $block->getUrl("media/images/")?>heart.png"/>                          
        </li>
        <li class="header__mobile-item">
            <img src="<?php echo $block->getUrl("media/images/")?>cart.png"/>       
        </li>
    </ul>

    <div class="header__category hide-on-mobi show-on-pc-flex">
        <ul class=" header__category-list">
            <li class="header__category-item">
                <a href="" class="header__category-item-link header-active-2">
                    <p>Your</p>
                    Jewelry                                        
                </a>
            </li>
            <li class="header__category-item">
                <a href="" class="header__category-item-link">Engagement &amp; Wedding</a>
            </li>
            <li class="header__category-item">
                <a href="" class="header__category-item-link">Fashion &amp; More...</a>
            </li>                                 
        </ul>
    </div>




