<ul class="header__submenu-list">
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            rings
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            necklaces
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            earings
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            Brooches
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            anklets
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            nose pins
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            men
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            women
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            kids
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            couple
        </a>
    </li>
    <li class="header__submenu-item">
        <a href="" class="header__submenu-item-link">
            collections
        </a>
    </li>
</ul>
    